//
// Created by leixing on 2024/4/25.
//

#ifndef INC_001_HELLOWORLD_LESSON_068_VIRTUALDESTRUCTOR_H
#define INC_001_HELLOWORLD_LESSON_068_VIRTUALDESTRUCTOR_H

void virtualDestructorTest();


#endif //INC_001_HELLOWORLD_LESSON_068_VIRTUALDESTRUCTOR_H
